spring:
  application.name: spring_templates
  datasource:
    url: jdbc:mariadb://localhost:3306/lora
    username: root
    password: 7590sa12
    driver-class-name: org.mariadb.jdbc.Driver

  #    spring:
  #      web:
  #        resources:
  #          add-mappings: true


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    username: ${ELASTIC_USERNAME:elastic}
    password: ${ELASTIC_PASSWORD:lAiO34cN}
    uris: ${ELASTIC_URI:localhost:9200}
server:
  shutdown: graceful

app:
  jwt:
    secret: 7876cdc4a2678e831a7a4888bb3fb1ab42258978e29ac4fbd9d3ce9a8832a78f7507637534f69cb7c926a5a8de54e33d97bd84d45399a43891c1100a37a26408
    access_expires_after: 86400000
    refresh_expires_after: 172800000
    issuer: jombi
  elasticsearch:
    is-ssl: ${ELASTIC_CERT_ENABLED:false}
    certificate: ${ELASTIC_CERT_PATH:}
    cert-password: ${ELASTIC_CERT_PASSWORD:}

    # 나중에는 없애야 함
    app:
      bucket:
        localDirectory: C:/images

# 나중에 주석 풀어야 함.
#  image:
#    manager-type: ${MANAGER_TYPE:LOCAL}


springdoc:
  api-docs:
    enabled: true
  enable-kotlin: true
  enable-javadoc: true
  swagger-ui:
    enabled: true
  trim-kotlin-indent: true
  use-fqn: true

logging:
  level:
    org.springframework.web: DEBUG
    com.dipvision.lora.api.facility.controller.FacilityController: DEBUG  # 'yourpackage'는 실제 패키지 이름으로 바꿔주세요.
